### ISSUE TITLE
Please add an open source license to this project

### ISSUE THREAD

**Issue by obscurerichard** [elthrasher/sam-typescript-webpack-sample#1]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://opensource.org/licenses/MIT

(replace the copyright statement with your copyright, of course)

**Comment by elthrasher** [comment]
You got it @obscurerichard.

**Comment by obscurerichard** [comment]
🙇  _**THANK YOU**_

One of my geek habits: [creating and bulldogging issues just like this](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aobscurerichard+archived%3Afalse+please+license+) :shipit:
